# -*- coding: utf-8 -*-
"""
Automatically generated by Colaboratory.

"""

# Find minimum value 
a = int(input("Enter the number: "))
b = int(input("Enter the number: "))
c = int(input("Enter the number: "))
d = int(input("Enter the number: "))
e = int(input("Enter the number: "))
if a < b:
  if a < c:
    if a < d:
      if a < e:
        print("a is small")
      else:
        print("e is small")

    else:
        if d < e:
          print("d is small")
        else:
          print("e is small")

  else:
        if c < d:
          if c < e:
            print("c is small")
          else:
            print("e is small")
      
        else:
              if b < c:
                if b < d:
                  if b < e:
                    print("b is small")
                  else:
                    print("e is small")

                else:
                    if d < e:
                      print("d is small")
                    else:
                      print("e is small")

              else:
                if c < d:
                  if c < e:
                    print("c is small")
                  else:
                    print("e is small")

# find 0 to 20:
for i in range(20):
  print('Hii, How are you', i)

# print odd & even number 15 to 35 :
for i in range(15,36):
  if(i%2==0):
    print(i, "Is even number")
  else:
    print(i, "Is odd number")

# Prime number

n = int(input("Enter number: "))
count=0
i=1
while(i<=n):
  if (n%i==0):
     count=count+1
  i=i+1
if(count==2):
    print("Prime number")
else:
    print("Not prime")



# Find number 6 to 15

a = int(input("Enter the number: "))
b = int(input("Enter the number: "))
for i in range(a,b):
  print(i)

# Nested loop:

for i in range(2):
  print(i,'Value of i')
  for j in range(1,3):
    print(j,'Value of j')

# Pattern:

for i in range(1,6):
  print("*"*(i))

for i in range(5,0,-1):
  print("@"*(i))

# Prime number / Range = 20:

a=0
while(a<=20):
  i=1
  count=0
  while(i<=a):
    if(a%i==0):
           count=count+1
    i=i+1
  if(count==2):
    print(a)
  a=a+1

# Print odd and even number/ range 15 to 25

a = 15
b = 26
while a < b:
  if a%2==0:
    print(a,'is even')
  else:
    print(a,'is odd')
  a+=1

# Vowels (find total vowels & Consonant)

a = input("Enter string: ")
vowel=0
cons=0
for i in range(0,len(a)):
  if(a[i]!=" "):
    if(a[i]=="a" or a[i]=="e" or a[i]=="i" or a[i]=="o" or a[i]=="u" 
       or a[i]=="A" or a[i]=="E" or a[i]=="I" or a[i]=="O" or a[i]=="U"):
           vowel=vowel+1
  else:
    cons=cons+1
print("Total vowel=", vowel)
print("Total cons=", cons)



# Write a program to perform addition/ subtraction/ multiplication/ division in the same program.

a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))
add=a+b
sub=a-b
mul=a*b
div=a/b
print("Addition=",add)
print("Subtraction=",sub)
print("Multiplication=",mul)
print("Division=",div)

# Write a program to swap value of two numbers.

a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))
print("Befoar swap a=",a)
print("Beafor swap b=",b)
c=a
a=b
b=c
print("After swap a=",a)
print("After swap b=",b)

# Write a program to calculate:
# Area of Rectangle/ Perimeter of rectangle/ Area of Square/
# Perimeter of Square/ Area of Circle/ Circumference of Circle

width = float(input("Enter the width of the rectangle: "))
length = float(input("Enter the length of the recteangle: "))

area = width * length
perimeter = (width + length)*2

print("Area of the rectangle is %.2f"%area)
print("Perimeter of the rectangle is %.2f"%perimeter)

# Area of square 

side = int(input("Enter side of square\n"))

area = side * side
print("Area of square is " + str(area))

# Perameter of square

side=float(input("Enter side of square: "))
print("Perimeter of square is",4*side)

# Area of circle

radius=int(input("Enter radius of a circle: "))
a = 3.14*radius**2
print("Area of circle is",a)

# Circumference of circle

PI = 3.14
radius=float(input("Enter the radius of a circle: "))
circumference = 2*PI*radius

print("Circumference of a circle = %.2f" % circumference)

# electricity unit bill

cost = int(input("Enter the cost price: "))
dis = int(input("Enter discount percentage: "))
#bill = cost*5
discount = dis * cost/100
bill = cost-discount
print("Discount is",discount)
print("total cost",bill)

# Prime number
n = int(input("Enter number: "))
count = 0
i=1
while(i<=n):
  if(n%i==0):
    count=count+1
  i=i+1
if(count==2):
  print("Prime number")
else:
  print("Not prime")

# factoriel number
n = int(input("Enter number: "))
fac = 1
while(n>0):
  fac=fac*n
  n=n-1
print(fac)

# fibonacci series
n = int(input("Enter number: "))
x = 0
y = 1
z = 0
while(z<=n):
  print(z)
  x = y
  y = z
  z = x + y

# pelindrome number
n = int(input("Enter number: "))
rev = 0
x = n
while(n>0):
  rev=(rev*10)+n%10
  n=n//10
if(x==rev):
  print("Pelindrome number")
else:
  print("Not pelindrome")



# Task Pizza and Pasta:


print("Welcome to Amazing Pizza and Pasta Pizzeria".center(80))

print("press 1 : order menu Pizza")
# print("press 2 : order menu Pasta")
print("press 2 : Exit")
choice = int(input("Enter your choice: "))
if choice == 1:
  print("1. Large pizza = 10.99")
  print("2. Large pizzas = 20.99")
  print("3. Large pizzas = 29.99")
  print("Buy 4 or more pizza and get 1.5 ltr of soft drink free".center(60,"*"))

  a = input("Enter your name: ")
  print("Welcome,",a)

  b = int(input("Enter number pizza order you want: "))
  print("1 : Large pizza",10.99)
  print("2 : Large pizza",20.99)
  print("3 : Large pizza",29.99)
  if b == 1:
    quty = int(input("Enter how many pizza you want...? : "))
    print("1 : Large pizza",10.99)
    cost = float(input("Enter cost : "))
    bill = cost * quty
    print("Your total pizza amount is : ",bill)
    if quty >= 4:
      print("Congratulations !! 1.5 ltr softdrink Free".center(60,"*"))
    else:
      print("Your order is completed... Thank You ...")
  elif b == 2:
    quty = int(input("Enter how many pizza you want...? : "))
    print("2 : Large pizza",20.99)
    cost = float(input("Enter cost : "))
    bill = cost * quty
    print("Your total pizza amount is : ",bill)
    if quty >= 4:
      print("Congratulations !! 1.5 ltr softdrink Free".center(60,"*"))
    else:
      print("Your order is completed... Thank You ...")
  elif b == 3:
    quty = int(input("Enter how many pizza you want...? : "))
    print("3 : Large pizza",29.99)
    cost = float(input("Enter cost : "))
    bill = cost * quty
    print("Your total pizza amount is : ",bill)
    if quty >= 4:
      print("Congratulations !! 1.5 ltr softdrink Free".center(60,"*"))
    else:
      print("Your order is completed... Thank You ...")


elif choice == 2:
  print("Exit")
else:
  print("Invalid syntax")


######### PASTA 

print("press 1 : order menu Pasta")
print("press 2 : Exit")
choice1 = int(input("Enter your choice: "))
if choice1 == 1:
  print("1. Large pasta = 9.5")
  print("2. Large pasta = 17.00")
  print("3. Large pasta = 27.50")
  print("Buy 4 or more pastas and get 2 bruschetta free".center(50,"*"))
  print("Buy 4 or more pizzas and pastas and get 2 chocco brownies ice-cream free.".center(80,"*"))


  c = int(input("Enter number pasta order you want: "))
  print("1 : Large pasta",9.5)
  print("2 : Large pastas",17.00)
  print("3 : Large pastas",27.50)
  if c == 1:
    quty1 = int(input("Enter how many Pasta you want...? : "))
    print("1 : Large pasta",9.5)
    cost = float(input("Enter cost : "))
    bill1 = cost * quty1
    print("Your total Pasta amount is : ",bill1)
    if quty1 >= 4:
      print("Congratulations !! get 2 bruschetta Free".center(60,"*"))
    else:
      print("Your order is completed... Thank You ...")
  if c == 2:
    quty1 = int(input("Enter how many Pasta you want...? : "))
    print("2 : Large pastas",17.00)
    cost = float(input("Enter cost : "))
    bill1 = cost * quty1
    print("Your total pasta amount is : ",bill1)
    if quty1 >= 4:
      print("Congratulations !! get 2 bruschetta Free".center(60,"*"))
    else:
      print("Your order is completed... Thank You ...")
  if c == 3:
    quty1 = int(input("Enter how many Pasta you want...? : "))
    print("3 : Large pasta",27.50)
    cost = float(input("Enter cost : "))
    bill1 = cost * quty1
    print("Your total Pasta amount is : ",bill1)
    if quty1 >= 4:
      print("Congratulations !! get 2 bruschetta Free".center(60,"*"))
    else:
      print("Your order is completed... ")

  if quty & quty1 >= 4:
    print("Congratulations !! get 2 chocco brownies ice-cream Free".center(60,"*"))
    print("Thank You...")
  else:
      print("Thank you....")

  
  total = bill + bill1
  print("Your Total order is : ",total)


elif choice == 2:
  print("Exit")
else:
  print("Invalid syntax")

# IPL TASK FUCNCTION:- 

import random
title = "WELCOME TO IPL 2022"
print(title.center(300))

ipl_team = ["CSK","MI","RCB","RR","LSG","GT","KXIP","KKR","SRH","DC"]
score_list = [0,1,2,4,6,"WICKET","NO BALL","WIDE","WICKET",6,0]

for team in ipl_team:
    print(team,end=" ")

my_team = input("\n\nEnter your team name : ").upper()
opp_team = ""

my_team_score = 0
opp_team_score = 0

m_ball = 0
o_ball = 0 

m_wicket = 0
o_wicket = 0

batting_team = ""

menu = """ 
                    press 1 for BAT
                    press 2 for BOWL
                """
def game():    
    global my_team,opp_team    
    if my_team in ipl_team:
        ipl_team.remove(my_team)
        opp_team = random.choice(ipl_team)
        print("\n MY TEAM : ",my_team)
        print("\n OPP. TEAM : ",opp_team)
    else:
        print("Invalid Name")


def toss_time(my_team,opp_team):
    global menu,batting_team
    print("\n\n TOSS (H/T) ")
    choice = input("Enter your choice (H/T) : ")
    toss = ("H","T")
    actual_toss = random.choice(toss)
    if choice==actual_toss:
        print(f"{my_team} WON THE TOSS")
        print(menu)
        
        selection = int(input("Enter your choice : "))
        
        if selection == 1:
            print(f"{my_team} choose bat first ")
            batting_team = my_team
            
        else:
            print(f"{my_team} choose bowl first ")
            batting_team = opp_team
            
    else:
        selection = random.randint(1,2)
        if selection == 1:
            batting_team = opp_team
            print(f"{opp_team} choose bat first ")
        else:
            batting_team = my_team
            print(f"{opp_team} choose bowl first ")
    print("---> batting team : ",batting_team)
        
def score_board(my_team,opp_team,batting_team):
    global my_team_score,opp_team_score,score_list,m_ball,o_ball,m_wicket,o_wicket
    if batting_team == my_team:
        while m_ball<10:
            m_ball += 1
            input()
            score = random.choice(score_list)
            if score=="WICKET":
                m_wicket += 1
                if m_wicket == 2:
                    print(f"{my_team} {my_team_score}/{m_wicket} ({m_ball} ball)  : {score}")
                    m_ball = 11
                else:
                    print(f"{my_team} {my_team_score}/{m_wicket} ({m_ball} ball)  : {score}")
            elif score=="WIDE" or score=="NO BALL":
                m_ball -= 1
                my_team_score += 1
                print(f"{my_team} {my_team_score}/{m_wicket} ({m_ball} ball)  : {score}")
            else:
                my_team_score += score
                print(f"{my_team} {my_team_score}/{m_wicket} ({m_ball} ball)  : {score}")
    else:
        while o_ball<10:
            o_ball += 1
            input()
            score = random.choice(score_list)
            if score=="WICKET":
                o_wicket += 1
                if o_wicket == 2:
                    print(f"{opp_team} {opp_team_score}/{o_wicket} ({o_ball} ball)  : {score}")    
                    o_ball=11
                else:
                    print(f"{opp_team} {opp_team_score}/{o_wicket} ({o_ball} ball)  : {score}")    
            elif score=="WIDE" or score=="NO BALL":
                o_ball -= 1
                opp_team_score += 1
                print(f"{opp_team} {opp_team_score}/{o_wicket} ({o_ball} ball)  : {score}")
            else:
                opp_team_score += score
                print(f"{opp_team} {opp_team_score}/{o_wicket} ({o_ball} ball)  : {score}")



game()
toss_time(my_team,opp_team)
play = 0
# print("---> play",play)
# print("---> bating name ",batting_team)
while play<=2:
    if batting_team==my_team:
        score_board(my_team,opp_team,my_team)
        batting_team = opp_team
        # print("--------> else -- bat",batting_team)
    else:
        score_board(my_team,opp_team,opp_team)
        batting_team = my_team
        # print("--> else -- bat",batting_team)
    play+=1 

if my_team_score>opp_team_score:
    print(f"{my_team} won the match !!")
else:
    print(f"{opp_team} won the match !!")

def evenodd(num):
  if num % 2 == 0:
      print("is even number")
  else:
      print("is odd number") 

a = int(input("enter a number: "))
evenodd(a)

# JAY BHAVANI VADAPAV TASK
jaybhavani = {
    "vadapav" : 30,
    "dabeli" : 25,
    "bhel" : 70,
}

mycart = []

status = True
while status:
  print("----MENU----")
  for k,v in jaybhavani.items():
    print(f"{k} = {v}")

  product = input("Enter product name : ").lower()
  if product in jaybhavani.keys():
    price = jaybhavani[product]
    print("product price is : ",price)

    qty = int(input("How many qty do you want : "))
    total_price = price * qty
    mycart.append(total_price)

  choice = input("do you want to purchase more items :press 'y' for yes and pree 'n' for no : ").lower()
  if choice == 'y' or choice == 'yes':
    status = True
  else:
    status = False

print("TOTAL PRICE = ", sum(mycart))