# Generated by Django 4.0.5 on 2022-07-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_chairman_block_no_chairman_house_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='media/default_chairman.png', upload_to='media/images/'),
        ),
    ]
