# Generated by Django 4.0.5 on 2022-07-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_chairman_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='about_me',
            field=models.TextField(null=True),
        ),
    ]
