# Generated by Django 4.0.5 on 2022-07-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_chairman_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='media/default_chairman.png', upload_to='myproject/'),
        ),
    ]
