# Generated by Django 4.0.5 on 2022-07-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='family_members',
            field=models.IntegerField(null=True),
        ),
    ]
