# Generated by Django 4.0.5 on 2022-07-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_member_family_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pic',
            field=models.FileField(default='media/default_chairman.png', upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='vehicle',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='work',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
