# Generated by Django 4.0.5 on 2022-07-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_about_member_member_about_me'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='about_me',
            new_name='about_member',
        ),
    ]
