# Generated by Django 4.0.5 on 2022-07-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_notice_remove_member_pic_member_contact_notice_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='video',
            field=models.FileField(null=True, upload_to='media/video/'),
        ),
    ]
