# Generated by Django 4.0.5 on 2022-07-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_member_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_id',
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
