# Generated by Django 4.0.5 on 2022-07-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_member_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
