# Generated by Django 4.0.5 on 2022-07-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Date_Time',
        ),
        migrations.AddField(
            model_name='event',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Time',
            field=models.TimeField(null=True),
        ),
    ]
