# Generated by Django 4.0.5 on 2022-07-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_event_date_time_event_date_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pic',
            field=models.FileField(default='media/default_chairman.png', upload_to='media/images/'),
        ),
    ]
