# Generated by Django 4.0.5 on 2022-07-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_watchman'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchman',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
