# Generated by Django 4.0.5 on 2022-07-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_watchman_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, null=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('contact', models.IntegerField(null=True)),
                ('pic', models.FileField(default='media/default_chairman.png', upload_to='media/images/')),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
