# Generated by Django 4.0.5 on 2022-07-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='Nametomeet',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='block_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='house_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
